# Generated by Django 5.0.6 on 2024-07-04 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "deviceId",
                    models.CharField(
                        editable=False,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("deviceName", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="HumidityReadings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("humid", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DeviceApp.device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemperatureReadings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("temp", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DeviceApp.device",
                    ),
                ),
            ],
        ),
    ]
