# Generated by Django 5.0.6 on 2024-07-04 17:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DeviceApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="deviceId",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
